# Generated by Django 3.2.25 on 2024-05-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp10_app', '0003_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
