# Generated by Django 5.0.2 on 2024-04-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_room_first_user_alter_room_second_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type_of',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
